name: CI
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.ci_node_index }}
    strategy:
      matrix:
        ruby:
          - '3.3.0-preview2'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        ci_node_total: [10]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    env:
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up JavaScript
      uses: actions/setup-node@v3
    - name: Steep check
      run: bundle exec steep check
    - name: Run the default task
      run: bundle exec rake
