name: Update parsed csv
on:
  pull_request:
    types: [opened]

jobs:
  update_parsed_csv:
    # /jsの中のnpmパッケージが更新されたプルリクエストに対してのみ実行する。
    if:  startsWith(github.head_ref, 'dependabot/submodules/geolonia-japanese-addresses')

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Update parsed csv
      run: bundle exec rake japanese_address_parser:parse_csv
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "[Automatic] Update parsed csv."
        git push
